# Generated by Django 5.0.3 on 2024-03-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("course_title", models.CharField(max_length=30)),
                ("course_description", models.CharField(max_length=50)),
                ("credit", models.IntegerField()),
                ("instructor", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
            ],
        ),
    ]
